name: Deploy
on: [push, workflow_dispatch]

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: rint working directory
        run: |
          pwd
          ls -a
          echo $GITHUB_WORKSPACE
          node -v
          npm -v
          npx -v
          echo "Test Passed"

  build-code:
    needs: test-code
    runs-on: ubuntu-latest

    steps:
      - name: Copy the code
        uses: andstor/copycat-action@v3
        run: echo "Copy Completed"