name: Deploy
on: [push, workflow_dispatch]

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: print working directory
        run: |
          pwd
          ls -a
          echo $GITHUB_WORKSPACE
          node -v
          npm -v
          npx -v
          echo Test Passed
  build-code:
    runs-on: ubuntu-latest
    steps: 
      needs: est-code
      -name: Copy the code
      uses: andstor/copycat-action@v3